"""add category and photos to finished_products

Revision ID: 07018c474570
Revises: 439bdf3d3b72
Create Date: 2026-06-18 15:28:28.943572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07018c474570'
down_revision: Union[str, None] = '439bdf3d3b72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finished_products', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('finished_products', sa.Column('photos', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finished_products', 'photos')
    op.drop_column('finished_products', 'category')
    # ### end Alembic commands ###
