"""add dict tables

Revision ID: 6a2fce49d8fd
Revises: 7ca4ad1a501a
Create Date: 2026-06-18 16:02:22.649921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a2fce49d8fd'
down_revision: Union[str, None] = '7ca4ad1a501a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dict_entries',
    sa.Column('dict_type_code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dict_entries_dict_type_code'), 'dict_entries', ['dict_type_code'], unique=False)
    op.create_index(op.f('ix_dict_entries_id'), 'dict_entries', ['id'], unique=False)
    op.create_table('dict_types',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_dict_types_id'), 'dict_types', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dict_types_id'), table_name='dict_types')
    op.drop_table('dict_types')
    op.drop_index(op.f('ix_dict_entries_id'), table_name='dict_entries')
    op.drop_index(op.f('ix_dict_entries_dict_type_code'), table_name='dict_entries')
    op.drop_table('dict_entries')
    # ### end Alembic commands ###
