"""add approval tables

Revision ID: 8987c279ce24
Revises: e9fdb7ca5326
Create Date: 2026-06-18 19:08:58.840952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8987c279ce24'
down_revision: Union[str, None] = 'e9fdb7ca5326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_flows',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('business_type', sa.String(length=50), nullable=False),
    sa.Column('trigger_condition', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_flows_business_type'), 'approval_flows', ['business_type'], unique=False)
    op.create_index(op.f('ix_approval_flows_id'), 'approval_flows', ['id'], unique=False)
    op.create_table('approval_instances',
    sa.Column('flow_id', sa.Integer(), nullable=False),
    sa.Column('business_type', sa.String(length=50), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('initiator_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('current_node_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['approval_flows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_instances_business_type'), 'approval_instances', ['business_type'], unique=False)
    op.create_index(op.f('ix_approval_instances_id'), 'approval_instances', ['id'], unique=False)
    op.create_table('approval_nodes',
    sa.Column('flow_id', sa.Integer(), nullable=False),
    sa.Column('node_order', sa.Integer(), nullable=False),
    sa.Column('node_name', sa.String(length=100), nullable=False),
    sa.Column('approver_type', sa.String(length=20), nullable=False),
    sa.Column('approver_value', sa.String(length=100), nullable=False),
    sa.Column('action_on_reject', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['approval_flows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_nodes_id'), 'approval_nodes', ['id'], unique=False)
    op.create_table('approval_records',
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['approval_instances.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['approval_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_records_id'), 'approval_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_records_id'), table_name='approval_records')
    op.drop_table('approval_records')
    op.drop_index(op.f('ix_approval_nodes_id'), table_name='approval_nodes')
    op.drop_table('approval_nodes')
    op.drop_index(op.f('ix_approval_instances_id'), table_name='approval_instances')
    op.drop_index(op.f('ix_approval_instances_business_type'), table_name='approval_instances')
    op.drop_table('approval_instances')
    op.drop_index(op.f('ix_approval_flows_id'), table_name='approval_flows')
    op.drop_index(op.f('ix_approval_flows_business_type'), table_name='approval_flows')
    op.drop_table('approval_flows')
    # ### end Alembic commands ###
