"""enhance_procurement_item_type_returns

Revision ID: edff1740befd
Revises: 0e152eb4caa2
Create Date: 2026-06-19 12:45:05.969604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edff1740befd'
down_revision: Union[str, None] = '0e152eb4caa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_returns',
    sa.Column('return_no', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('return_no')
    )
    op.create_index(op.f('ix_purchase_returns_id'), 'purchase_returns', ['id'], unique=False)
    op.create_table('purchase_return_items',
    sa.Column('return_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_item_id'], ['purchase_order_items.id'], ),
    sa.ForeignKeyConstraint(['return_id'], ['purchase_returns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_return_items_id'), 'purchase_return_items', ['id'], unique=False)
    op.add_column('purchase_order_items', sa.Column('item_type', sa.String(length=20), nullable=True))
    op.add_column('purchase_order_items', sa.Column('product_id', sa.Integer(), nullable=True))
    op.alter_column('purchase_order_items', 'material_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'purchase_order_items', 'finished_products', ['product_id'], ['id'])
    op.execute("UPDATE purchase_order_items SET item_type = 'material' WHERE item_type IS NULL")
    op.add_column('purchase_request_items', sa.Column('item_type', sa.String(length=20), nullable=True))
    op.add_column('purchase_request_items', sa.Column('product_id', sa.Integer(), nullable=True))
    op.alter_column('purchase_request_items', 'material_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'purchase_request_items', 'finished_products', ['product_id'], ['id'])
    op.execute("UPDATE purchase_request_items SET item_type = 'material' WHERE item_type IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase_request_items', type_='foreignkey')
    op.alter_column('purchase_request_items', 'material_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('purchase_request_items', 'product_id')
    op.drop_column('purchase_request_items', 'item_type')
    op.drop_constraint(None, 'purchase_order_items', type_='foreignkey')
    op.alter_column('purchase_order_items', 'material_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('purchase_order_items', 'product_id')
    op.drop_column('purchase_order_items', 'item_type')
    op.drop_index(op.f('ix_purchase_return_items_id'), table_name='purchase_return_items')
    op.drop_table('purchase_return_items')
    op.drop_index(op.f('ix_purchase_returns_id'), table_name='purchase_returns')
    op.drop_table('purchase_returns')
    # ### end Alembic commands ###
